name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: echo "не надо"

    - name: Install dependencies
      run: make

    - name: Run check
      run: echo "работает"

    - name: Run distcheck
      run: echo "не надо"
